import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <div className='border-4 border-red-200 bg-yellow-400 h-[20rem] '></div>
      </Head>

      

    </div>
  )
}
